name: Update Publications Metrics

on:
  pull_request:
    branches:
      - main
    paths:
      - 'data/publications.yml'
    
jobs:
  update_metrics:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v2
    - shell: pwsh
      run: echo publish docs
  
    - name: Install dependencies
      run: |
        python -m pip install pip --upgrade
        python -m pip install ruamel.yaml pre-commit
          
    - name: Update publications metrics
      shell: python
      run: |
        from ruamel.yaml import YAML
        yaml = YAML()

        publications_file = 'data/publications.yml'
        metrics_file = 'data/metrics.yml'
          
        with open(publications_file) as f:
          publications_dict = yaml.load(f)
          number = len(publications_dict['items'])

        with open(metrics_file, 'r+') as f:
          metrics_dict = yaml.load(f)
          metrics_dict['counter_item'][1][number] = number
          yaml.dump(metrics_dict, f)

    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: 'Update metrics.yml'
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        base: main
        title: 'Update metrics.yml'
        body: |
          Update `metrics.yml` from updates to `publications.yml`
        token: ${{ secrets.VAST_METRICS }}
        branch: auto-metrics
